spring.application.name=TaskMate

# Swagger config
spring.ai.openai.api-key=dummy
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

app.jwt.secret=G6XZlZl94oB1vjUt0O3/Yc5IlK+qQhKyUEfXcJ0y4Pg=


# Cache
spring.cache.type=simple

# Logging
logging.level.org.springframework.web=DEBUG

server.port=8080

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#spring.security.oauth2.client.registration.google.client-id=YOUR_GOOGLE_CLIENT_ID
#spring.security.oauth2.client.registration.google.client-secret=YOUR_GOOGLE_CLIENT_SECRET
#spring.security.oauth2.client.registration.google.scope=email,profile
#spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
#spring.security.oauth2.client.registration.google.client-name=Google
#spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/auth
#spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
#spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo