name: Deploy to S3

on:
  pull_request:
    branches:
      - main
      - development

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
    
        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '18'

        - name: Install dependencies
          run: |
           npm install
           npm install bootstrap @types/bootstrap --save
          working-directory: ./View/TaskMate
        
        - name: Build project
          run: npm run build
          working-directory: ./View/TaskMate

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1
    
        - name: Deploy to S3
          run: |
            export AWS_MAX_CONCURRENT_REQUESTS=50
            aws s3 sync ./dist s3://job-mate/TaskMate/${{ github.ref_name }}/ \
                --exact-timestamps \ --delete \ --acl public-read

